### ISSUE TITLE
Angular not bundled with browserify

### ISSUE THREAD

**Issue by nioe** [javoire/browserify-ng-html2js#19]
With the Version 1.1.1 you require angular within the template module (Introduced with commit 064a5686215362d2f58f2152f918e4d9b15a1960).

This does not work if Angular isn't bundled with browserify.

__Error: Cannot find module 'angular'__

**Comment by teddyhwang** [comment]
Similar to the issue of angular versions that don't support commonjs: https://github.com/javoire/browserify-ng-html2js/issues/18

**Comment by javoire** [comment]
e6b7ee39d8ebbc42523e713d40dec08226465e56
